### ISSUE TITLE
include/exclude in usercss header

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/parse-usercss#7]
See the discussion in https://github.com/openstyles/stylus/issues/113. In summary, `@document` or the `-moz-` variant isn't going to be implemented in browsers anytime soon and there's also the issue that it does not support any kind of exclude pattern (yes, this can be remedied via negative regex, but that's not user friendly).

I was thinking we could allow include/exclude in the usercss header. Obviously, this won't allow for multiple sections or nesting, but I guess most styles out there only use on section anyways and if more are needed, multiple styles can be written instead.

Here's what greasemonkey supports: https://wiki.greasespot.net/Include_and_exclude_rules

I think having both globs and regexes (wrapped in /, but otherwise fully JS-compatible regex) for include and exclude provides enough flexibility for the author. I'd wager the UI of Stylus would have to be changed if we implement this as it currently supports multiple `@-moz-document` rules.

**Comment by eight04** [comment]
I think this thread should be moved to openstyles/stylus since it is a request about [usercss spec](https://github.com/openstyles/stylus/wiki/Usercss). If Stylus accepts, we can add `include`, `exclude` to `KNOWN_META`.

https://github.com/StylishThemes/parse-usercss/blob/272610bb4a67d02ba62fe593c327282da403d95f/index.js#L5-L20

Also note that in the very first version of usercss, it did have [include/exclude headers](https://github.com/openstyles/stylus/pull/134#issuecomment-321324391), but then we decided to replace it with traditional `@-moz-document` rule.


> @document or the -moz- variant isn't going to be implemented in browsers anytime soon

This is not an issue since the extension doesn't actually rely on this feature. The extension parses the directive and extracts the CSS code. When the URL matches the directive, the CSS code is injected to the page. Also, this is the reason why Stylus can work on Google Chrome.

**Comment by silverwind** [comment]
> This is not an issue since the extension doesn't actually rely on this feature.

Yes, I realize that. I just thought that the initial idea when `@-moz-document` was introduced was that this will eventually be supported by all browsers. In reality, this won't happen so I think we need alternatives.

Moving to https://github.com/openstyles/stylus/issues/343.
